CREATE OR REPLACE MODULE UTL_ENCODE@

ALTER MODULE UTL_ENCODE PUBLISH
FUNCTION BASE64_DECODE (IN r VARBINARY(32672)) RETURNS VARBINARY(32672)
EXTERNAL NAME 'UTL_ENCODE!BASE64_DECODE' 
FENCED
PARAMETER STYLE JAVA
LANGUAGE JAVA
NO EXTERNAL ACTION
@

ALTER MODULE UTL_ENCODE PUBLISH
FUNCTION BASE64_ENCODE(IN r VARBINARY(32672)) RETURNS VARBINARY(32672)
EXTERNAL NAME 'UTL_ENCODE!BASE64_ENCODE' 
FENCED
PARAMETER STYLE JAVA
LANGUAGE JAVA
NO EXTERNAL ACTION 
@  
  
